<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_QxbNQEXPEfCMIvdXAFdhzA" name="Rececao_Equipamento_Suporte" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_Q-9S8EXPEfCMIvdXAFdhzA" name="Receção de Equipamento para Suporte">
      <elements xmi:type="process:ServiceTask" xmi:id="_Q_LVYEXPEfCMIvdXAFdhzA" name="Preencher o Pedido de Serviço “FOR_SU_Pedido-de-serviço”" outgoing="_RH8P0EXPEfCMIvdXAFdhzA" incoming="_RH2wQEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_LVYkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_LVYUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_L8cEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Q_L8cUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Q_L8ckXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q_L8c0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q_L8dUXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Q_L8dEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:StartMessageEvent" xmi:id="_Q_Q08EXPEfCMIvdXAFdhzA" name="Inicio de pedido de suporte" outgoing="_RH2wQEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_RcAUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_RcAEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_RcAkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_Q_fecEXPEfCMIvdXAFdhzA" name="Cancelar receção de pedido para suporte" outgoing="_RIFZwEXPEfCMIvdXAFdhzA" incoming="_ibbXkEXUEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_feckXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_fecUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_gFgEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Q_gFgUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Q_gFgkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q_gFg0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q_gFhUXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Q_gFhEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_Q_qdkEXPEfCMIvdXAFdhzA" name="Pedir assinatura do cliente" outgoing="_udW4YEXUEfCMIvdXAFdhzA" incoming="_RH8P0EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_qdkkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_qdkUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_qdk0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Q_qdlEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Q_qdlUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q_qdlkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q_qdmEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Q_qdl0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_Q_uvAEXPEfCMIvdXAFdhzA" name="Pedido cancelado" incoming="_RIFZwEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_uvAkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_uvAUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_uvA0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_Q_7jUEXPEfCMIvdXAFdhzA" name="Receção end" outgoing="_RIuS8EXPEfCMIvdXAFdhzA" incoming="_RImXIEXPEfCMIvdXAFdhzA _RIqokEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_8KYUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_8KYEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_8KYkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RAAb0EXPEfCMIvdXAFdhzA" name="Acordar data para recolha do equipamento" outgoing="_RIykYEXPEfCMIvdXAFdhzA" incoming="_RIiswEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAAb0kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAAb0UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAAb00XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAAb1EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAAb1UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAAb1kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAAb2EXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAAb10XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_RAEtQEXPEfCMIvdXAFdhzA" name="Pedido cancelado" incoming="_RI2OwEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAFUUUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAFUUEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAFUUkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RALa8EXPEfCMIvdXAFdhzA" name="Cancelar pedido de suporte" outgoing="_RI2OwEXPEfCMIvdXAFdhzA" incoming="_WE8GkEXVEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RALa8kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RALa8UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RALa80XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RALa9EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RALa9UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RALa9kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RALa-EXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RALa90XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_RAQTcEXPEfCMIvdXAFdhzA" name="Notificação enviada" incoming="_RI-xoEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAQTckXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAQTcUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAQTc0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RAVL8EXPEfCMIvdXAFdhzA" name="Notificar cliente para enviar o produto" outgoing="_RI-xoEXPEfCMIvdXAFdhzA" incoming="_O9Y1EEXVEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAVzAUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAVzAEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAVzAkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAVzA0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAVzBEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAVzBUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAVzB0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAVzBkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ReceiveTask" xmi:id="_RAY2UEXPEfCMIvdXAFdhzA" name="Receber data para recolha" outgoing="_RJGtcEXPEfCMIvdXAFdhzA" incoming="_RIykYEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAY2UkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAY2UUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAY2U0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAY2VEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAY2VUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAY2VkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAY2WEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAY2V0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RAeV4EXPEfCMIvdXAFdhzA" name="Recolher produto" outgoing="_RIqokEXPEfCMIvdXAFdhzA" incoming="_RJGtcEXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAeV4kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAeV4UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAeV40XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAeV5EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAeV5UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAeV5kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAeV6EXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAeV50XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <BoundaryIntermediateEvents xmi:type="process:IntermediateErrorCatchEvent" xmi:id="_hgXBAEXVEfCMIvdXAFdhzA" name="Ciente não presente para recolha do produto" outgoing="_iPTxsEXVEfCMIvdXAFdhzA"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RAeV6kXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RAeV60XPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RAeV6UXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RAeV7EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RAjOYEXPEfCMIvdXAFdhzA" name="Preencher  formulário F-AST-04 (pedido de serviço)" outgoing="_RJK-4EXPEfCMIvdXAFdhzA" incoming="_RIuS8EXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAjOYkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAjOYUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAjOY0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAjOZEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAjOZUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAjOZkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAjOaEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAjOZ0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RAjOakXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RAjOa0XPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RAjOaUXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RAjObEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RAot8EXPEfCMIvdXAFdhzA" name="Identificar produto com etiqueta vermelha do tipo S identificada com &quot;R&quot;" outgoing="_RJOpQEXPEfCMIvdXAFdhzA" incoming="_RJK-4EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAot8kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAot8UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAot80XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAot9EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAot9UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAot9kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAot-EXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAot90XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RAtmcEXPEfCMIvdXAFdhzA" name="Verificar se é reparação física" outgoing="_RJSToEXPEfCMIvdXAFdhzA" incoming="_RJOpQEXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAtmckXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAtmcUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAtmc0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RAtmdEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RAtmdUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RAtmdkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RAtmeEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RAtmd0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RAtmekXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RAtme0XPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RAtmeUXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RAtmfEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RAxQ0EXPEfCMIvdXAFdhzA" name="Reparação física?" outgoing="_RJWlEEXPEfCMIvdXAFdhzA _RJa2gEXPEfCMIvdXAFdhzA" incoming="_RJSToEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RAx34UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RAx34EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RAx34kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RA2JUEXPEfCMIvdXAFdhzA" name="Abrir incidente na CRM" outgoing="_RJfH8EXPEfCMIvdXAFdhzA" incoming="_RJWlEEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RA2JUkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RA2JUUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RA2JU0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RA2JVEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RA2JVUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RA2JVkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RA2JWEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RA2JV0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RA6awEXPEfCMIvdXAFdhzA" name="Reparação física end" outgoing="_RJiyUEXPEfCMIvdXAFdhzA" incoming="_RJa2gEXPEfCMIvdXAFdhzA _RJfH8EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RA7B0UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RA7B0EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RA7B0kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RA-sMEXPEfCMIvdXAFdhzA" name="Tipo de prioridade" outgoing="_RJu_kEXPEfCMIvdXAFdhzA _RJzRAEXPEfCMIvdXAFdhzA _RKoXcEXPEfCMIvdXAFdhzA" incoming="_RJnDwEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RA_TQUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RA_TQEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RA_TQkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RBDksEXPEfCMIvdXAFdhzA" name="Pedir informação de como o produto irá ser entregue" outgoing="_RIV4cEXPEfCMIvdXAFdhzA" incoming="_RJquIEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBDkskXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBDksUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBDks0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RBDktEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RBELwEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RBELwUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RBELw0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RBELwkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ReceiveTask" xmi:id="_RBH2IEXPEfCMIvdXAFdhzA" name="Receber informação de como o produto será entregue" outgoing="_RIaJ4EXPEfCMIvdXAFdhzA" incoming="_RIV4cEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBH2IkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBH2IUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBH2I0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RBH2JEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RBH2JUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RBH2JkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RBH2KEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RBH2J0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RBLggEXPEfCMIvdXAFdhzA" name="Como será a receção do produto?" outgoing="_RId0QEXPEfCMIvdXAFdhzA _RIiswEXPEfCMIvdXAFdhzA" incoming="_RIaJ4EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBMHkUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBMHkEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBMHkkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RBPx8EXPEfCMIvdXAFdhzA" name="Verificar o tipo de prioridade de reparação" outgoing="_RJnDwEXPEfCMIvdXAFdhzA" incoming="_RJiyUEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBQZAUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBQZAEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBQZAkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RBQZA0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RBQZBEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RBQZBUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RBQZB0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RBQZBkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RBUDYEXPEfCMIvdXAFdhzA" name="Produto Preparado?" outgoing="_RJ7M0EXPEfCMIvdXAFdhzA _RJ-3MEXPEfCMIvdXAFdhzA" incoming="_RJ3icEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBUqcUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBUqcEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBUqckXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_RBYU0EXPEfCMIvdXAFdhzA" name="Pedido de suporte terminado" incoming="_RKDIoEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBYU0kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBYU0UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBYU00XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RBb_MEXPEfCMIvdXAFdhzA" name="Produto entregue?" outgoing="_RKDIoEXPEfCMIvdXAFdhzA _RKHaEEXPEfCMIvdXAFdhzA" incoming="_RLCnIEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBcmQUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBcmQEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBcmQkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_RBhewEXPEfCMIvdXAFdhzA" name="Garantia Procedimentos" outgoing="_RKP88EXPEfCMIvdXAFdhzA _RKTnUEXPEfCMIvdXAFdhzA" incoming="_RJu_kEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBhewkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBhewUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBhew0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ANDGateway" xmi:id="_RBr20EXPEfCMIvdXAFdhzA" name="Garantia Procedimentos end" outgoing="_RKLrgEXPEfCMIvdXAFdhzA" incoming="_RKYf0EXPEfCMIvdXAFdhzA _RKcxQEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBsd4UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBsd4EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBsd4kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RBwIQEXPEfCMIvdXAFdhzA" name="Estabelecer prioridade de nível 2" outgoing="_RKgboEXPEfCMIvdXAFdhzA" incoming="_RJzRAEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RBwIQkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RBwIQUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RBwIQ0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RBwIREXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RBwIRUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RBwIRkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RBwISEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RBwIR0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RB0ZsEXPEfCMIvdXAFdhzA" name="Estabelecer prioridade de nível 1" outgoing="_RKktEEXPEfCMIvdXAFdhzA" incoming="_RKoXcEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RB0ZskXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RB0ZsUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RB0Zs0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RB0ZtEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RB0ZtUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RB0ZtkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RB0ZuEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RB0Zt0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:XORGateway" xmi:id="_RB4EEEXPEfCMIvdXAFdhzA" name="Tipo prioridade end" outgoing="_RKw6UEXPEfCMIvdXAFdhzA" incoming="_RKso4EXPEfCMIvdXAFdhzA _RK0ksEXPEfCMIvdXAFdhzA _RK9uoEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RB4rIUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RB4rIEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RB4rIkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_RB8VgEXPEfCMIvdXAFdhzA" name="Pedido de Suporte Terminado com Problemas" incoming="_RJ7M0EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RB88kUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RB88kEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RB88kkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_RCBOAEXPEfCMIvdXAFdhzA" name="Pedido de Suporte Terminado com Problemas" incoming="_RKHaEEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCBOAkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCBOAUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCBOA0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RCFfcEXPEfCMIvdXAFdhzA" name="Registar na folha de obra" outgoing="_RKcxQEXPEfCMIvdXAFdhzA" incoming="_RKTnUEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCGGgUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCGGgEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCGGgkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCGGg0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCGGhEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCGGhUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCGGh0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCGGhkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ReceiveTask" xmi:id="_RCKX8EXPEfCMIvdXAFdhzA" name="Receber produto do fornecedor" outgoing="_RK0ksEXPEfCMIvdXAFdhzA" incoming="_RKLrgEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCKX8kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCKX8UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCKX80XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCKX9EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCKX9UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCKX9kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCKX-EXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCKX90XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RCOpYEXPEfCMIvdXAFdhzA" name="Enviar equipamento para fornecedor ou fabricante" outgoing="_RKYf0EXPEfCMIvdXAFdhzA" incoming="_RKP88EXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCPQcUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCPQcEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCPQckXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCPQc0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCPQdEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCPQdUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCPQd0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCPQdkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RCS60EXPEfCMIvdXAFdhzA" name="Notificar cancelamento por falta de presença" outgoing="_RK42IEXPEfCMIvdXAFdhzA" incoming="_iPTxsEXVEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCTh4UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCTh4EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCTh4kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCTh40XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCTh5EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCTh5UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCTh50XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCTh5kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndTerminatedEvent" xmi:id="_RCXzUEXPEfCMIvdXAFdhzA" name="Pedido suporte cancelado" incoming="_RK42IEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCXzUkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCXzUUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCXzU0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:SendTask" xmi:id="_RCcEwEXPEfCMIvdXAFdhzA" name="Enviar notificação ao cliente para assinar o documento a" outgoing="_fbYuBEXUEfCMIvdXAFdhzA" incoming="_hRAy4EXUEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCcr0UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCcr0EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCcr0kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCcr00XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCcr1EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCcr1UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCcr10XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCcr1kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:ServiceTask" xmi:id="_RCg9QEXPEfCMIvdXAFdhzA" name="Verificar se produto está pronto para entrega" outgoing="_RJ3icEXPEfCMIvdXAFdhzA" incoming="_RKw6UEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCg9QkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCg9QUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCg9Q0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCg9REXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCg9RUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCg9RkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCg9SEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCg9R0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RCl1wEXPEfCMIvdXAFdhzA" name="Diagnóstico e Reparação" outgoing="_RKso4EXPEfCMIvdXAFdhzA" incoming="_RKktEEXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCmc0UXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCmc0EXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCmc0kXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCmc00XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCmc1EXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCmc1UXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCmc10XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCmc1kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RCmc2UXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RCmc2kXPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RCmc2EXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RCmc20XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RCqHMEXPEfCMIvdXAFdhzA" name="Diagnóstico e Reparação" outgoing="_RK9uoEXPEfCMIvdXAFdhzA" incoming="_RKgboEXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCquQUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCquQEXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCquQkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCquQ0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCquREXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCquRUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCquR0XPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCquRkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RCquSUXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RCquSkXPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RCquSEXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RCquS0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_RCu_sEXPEfCMIvdXAFdhzA" name="Entrega" outgoing="_RLCnIEXPEfCMIvdXAFdhzA" incoming="_RJ-3MEXPEfCMIvdXAFdhzA" priority="1">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCu_skXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCu_sUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCu_s0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCu_tEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCu_tUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCu_tkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCu_uEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCu_t0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_RCu_ukXPEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_RCu_u0XPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_RCu_uUXPEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_RCu_vEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_c_y1UEXUEfCMIvdXAFdhzA" name="Receber assinatura do cliente" outgoing="_RJquIEXPEfCMIvdXAFdhzA" incoming="_udW4YEXUEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_Q_mzMkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_Q_mzMUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_Q_mzM0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_Q_mzNEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_Q_mzNUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Q_mzNkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_Q_mzOEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_Q_mzN0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_eAvU8EXUEfCMIvdXAFdhzA" name="2 Dias" outgoing="_hRAy4EXUEfCMIvdXAFdhzA"/>
        <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_h2znkEXUEfCMIvdXAFdhzA" name="7 Dias" outgoing="_ibbXkEXUEfCMIvdXAFdhzA"/>
        <formMapping xmi:type="process:FormMapping" xmi:id="_c_y1WkXUEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_c_y1W0XUEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_c_y1WUXUEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_c_y1XEXUEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:EndEvent" xmi:id="_fbYG8EXUEfCMIvdXAFdhzA" name="Notificado" incoming="_fbYuBEXUEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_fbYG8kXUEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_fbYG8UXUEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_fbYG80XUEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
      </elements>
      <elements xmi:type="process:Task" xmi:id="_CXV6kEXVEfCMIvdXAFdhzA" name="Receber produto" outgoing="_RImXIEXPEfCMIvdXAFdhzA" incoming="_RId0QEXPEfCMIvdXAFdhzA">
        <dynamicLabel xmi:type="expression:Expression" xmi:id="_RCzRIkXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <dynamicDescription xmi:type="expression:Expression" xmi:id="_RCzRIUXPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <stepSummary xmi:type="expression:Expression" xmi:id="_RCzRI0XPEfCMIvdXAFdhzA" name="" content="" returnTypeFixed="true"/>
        <loopCondition xmi:type="expression:Expression" xmi:id="_RCz4MEXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <loopMaximum xmi:type="expression:Expression" xmi:id="_RCz4MUXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <cardinalityExpression xmi:type="expression:Expression" xmi:id="_RCz4MkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
        <iteratorExpression xmi:type="expression:Expression" xmi:id="_RCz4NEXPEfCMIvdXAFdhzA" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
        <completionCondition xmi:type="expression:Expression" xmi:id="_RCz4M0XPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_LSZKAEXVEfCMIvdXAFdhzA" name="Cada 3 dias" outgoing="_O9Y1EEXVEfCMIvdXAFdhzA">
          <condition xmi:type="expression:Expression" xmi:id="_pTe_EEXVEfCMIvdXAFdhzA" name="3 Days 00:00:00" content="259200000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </BoundaryIntermediateEvents>
        <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_TWgKYEXVEfCMIvdXAFdhzA" name="10 Dias" outgoing="_WE8GkEXVEfCMIvdXAFdhzA">
          <condition xmi:type="expression:Expression" xmi:id="_nhSosEXVEfCMIvdXAFdhzA" name="10 Days 00:00:00" content="864000000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
        </BoundaryIntermediateEvents>
        <formMapping xmi:type="process:FormMapping" xmi:id="_CXWhqUXVEfCMIvdXAFdhzA">
          <targetForm xmi:type="expression:Expression" xmi:id="_CXWhqkXVEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
        </formMapping>
        <contract xmi:type="process:Contract" xmi:id="_CXWhqEXVEfCMIvdXAFdhzA"/>
        <expectedDuration xmi:type="expression:Expression" xmi:id="_CXWhq0XVEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
      </elements>
      <data xmi:type="process:Data" xmi:id="_Q_KHQEXPEfCMIvdXAFdhzA" name="DataObject_1jekx1y" dataType="_QxhT5UXPEfCMIvdXAFdhzA">
        <defaultValue xmi:type="expression:Expression" xmi:id="_Q_KHQUXPEfCMIvdXAFdhzA" name="" content="" returnType=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Q-9TAEXPEfCMIvdXAFdhzA">
        <targetForm xmi:type="expression:Expression" xmi:id="_Q-9TAUXPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Q-9TAkXPEfCMIvdXAFdhzA">
        <targetForm xmi:type="expression:Expression" xmi:id="_Q-9TA0XPEfCMIvdXAFdhzA" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RH2wQEXPEfCMIvdXAFdhzA" target="_Q_LVYEXPEfCMIvdXAFdhzA" source="_Q_Q08EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RH3XUEXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RH3XUUXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RH8P0EXPEfCMIvdXAFdhzA" target="_Q_qdkEXPEfCMIvdXAFdhzA" source="_Q_LVYEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RH8P0UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RH8P0kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIFZwEXPEfCMIvdXAFdhzA" target="_Q_uvAEXPEfCMIvdXAFdhzA" source="_Q_fecEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIFZwUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIFZwkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIV4cEXPEfCMIvdXAFdhzA" target="_RBH2IEXPEfCMIvdXAFdhzA" source="_RBDksEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIV4cUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIV4ckXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIaJ4EXPEfCMIvdXAFdhzA" target="_RBLggEXPEfCMIvdXAFdhzA" source="_RBH2IEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIaJ4UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIaJ4kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RId0QEXPEfCMIvdXAFdhzA" name="Cliente entrega na empresa" target="_CXV6kEXVEfCMIvdXAFdhzA" source="_RBLggEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RId0QUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RId0QkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIiswEXPEfCMIvdXAFdhzA" name="Recolhido pela empresa" target="_RAAb0EXPEfCMIvdXAFdhzA" source="_RBLggEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIiswUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIiswkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RImXIEXPEfCMIvdXAFdhzA" target="_Q_7jUEXPEfCMIvdXAFdhzA" source="_CXV6kEXVEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RImXIUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RImXIkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIqokEXPEfCMIvdXAFdhzA" target="_Q_7jUEXPEfCMIvdXAFdhzA" source="_RAeV4EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIqokUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIqokkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIuS8EXPEfCMIvdXAFdhzA" target="_RAjOYEXPEfCMIvdXAFdhzA" source="_Q_7jUEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIuS8UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIuS8kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RIykYEXPEfCMIvdXAFdhzA" target="_RAY2UEXPEfCMIvdXAFdhzA" source="_RAAb0EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RIykYUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RIykYkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RI2OwEXPEfCMIvdXAFdhzA" target="_RAEtQEXPEfCMIvdXAFdhzA" source="_RALa8EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RI2OwUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RI2OwkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RI-xoEXPEfCMIvdXAFdhzA" target="_RAQTcEXPEfCMIvdXAFdhzA" source="_RAVL8EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RI-xoUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RI-xokXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJGtcEXPEfCMIvdXAFdhzA" target="_RAeV4EXPEfCMIvdXAFdhzA" source="_RAY2UEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJGtcUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJGtckXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJK-4EXPEfCMIvdXAFdhzA" target="_RAot8EXPEfCMIvdXAFdhzA" source="_RAjOYEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJK-4UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJK-4kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJOpQEXPEfCMIvdXAFdhzA" target="_RAtmcEXPEfCMIvdXAFdhzA" source="_RAot8EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJOpQUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJOpQkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJSToEXPEfCMIvdXAFdhzA" target="_RAxQ0EXPEfCMIvdXAFdhzA" source="_RAtmcEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJSToUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJSTokXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJWlEEXPEfCMIvdXAFdhzA" name="Sim" target="_RA2JUEXPEfCMIvdXAFdhzA" source="_RAxQ0EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJWlEUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJWlEkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJa2gEXPEfCMIvdXAFdhzA" name="Não" target="_RA6awEXPEfCMIvdXAFdhzA" source="_RAxQ0EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJa2gUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJa2gkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJfH8EXPEfCMIvdXAFdhzA" target="_RA6awEXPEfCMIvdXAFdhzA" source="_RA2JUEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJfH8UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJfH8kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJiyUEXPEfCMIvdXAFdhzA" target="_RBPx8EXPEfCMIvdXAFdhzA" source="_RA6awEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJiyUUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJiyUkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJnDwEXPEfCMIvdXAFdhzA" target="_RA-sMEXPEfCMIvdXAFdhzA" source="_RBPx8EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJnDwUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJnDwkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJquIEXPEfCMIvdXAFdhzA" target="_RBDksEXPEfCMIvdXAFdhzA" source="_c_y1UEXUEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJquIUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJquIkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJu_kEXPEfCMIvdXAFdhzA" name="Garantia" target="_RBhewEXPEfCMIvdXAFdhzA" source="_RA-sMEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJu_kUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJu_kkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJzRAEXPEfCMIvdXAFdhzA" name="Pedido avulso" target="_RBwIQEXPEfCMIvdXAFdhzA" source="_RA-sMEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJzRAUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJzRAkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJ3icEXPEfCMIvdXAFdhzA" target="_RBUDYEXPEfCMIvdXAFdhzA" source="_RCg9QEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJ3icUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJ3ickXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJ7M0EXPEfCMIvdXAFdhzA" target="_RB8VgEXPEfCMIvdXAFdhzA" source="_RBUDYEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJ7M0UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJ7M0kXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RJ-3MEXPEfCMIvdXAFdhzA" target="_RCu_sEXPEfCMIvdXAFdhzA" source="_RBUDYEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RJ-3MUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RJ-3MkXPEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKDIoEXPEfCMIvdXAFdhzA" name="Sim" target="_RBYU0EXPEfCMIvdXAFdhzA" source="_RBb_MEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKDIoUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKDIokXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKHaEEXPEfCMIvdXAFdhzA" name="Não" target="_RCBOAEXPEfCMIvdXAFdhzA" source="_RBb_MEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKHaEUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKHaEkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKLrgEXPEfCMIvdXAFdhzA" target="_RCKX8EXPEfCMIvdXAFdhzA" source="_RBr20EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKMSkEXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKMSkUXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKP88EXPEfCMIvdXAFdhzA" target="_RCOpYEXPEfCMIvdXAFdhzA" source="_RBhewEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKP88UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKP88kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKTnUEXPEfCMIvdXAFdhzA" target="_RCFfcEXPEfCMIvdXAFdhzA" source="_RBhewEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKUOYEXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKUOYUXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKYf0EXPEfCMIvdXAFdhzA" target="_RBr20EXPEfCMIvdXAFdhzA" source="_RCOpYEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKYf0UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKYf0kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKcxQEXPEfCMIvdXAFdhzA" target="_RBr20EXPEfCMIvdXAFdhzA" source="_RCFfcEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKcxQUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKcxQkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKgboEXPEfCMIvdXAFdhzA" target="_RCqHMEXPEfCMIvdXAFdhzA" source="_RBwIQEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKgboUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKgbokXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKktEEXPEfCMIvdXAFdhzA" target="_RCl1wEXPEfCMIvdXAFdhzA" source="_RB0ZsEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKktEUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKktEkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKoXcEXPEfCMIvdXAFdhzA" name="Sujeito a contrato de assistência" target="_RB0ZsEXPEfCMIvdXAFdhzA" source="_RA-sMEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKoXcUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKoXckXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKso4EXPEfCMIvdXAFdhzA" target="_RB4EEEXPEfCMIvdXAFdhzA" source="_RCl1wEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKso4UXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKso4kXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RKw6UEXPEfCMIvdXAFdhzA" target="_RCg9QEXPEfCMIvdXAFdhzA" source="_RB4EEEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RKw6UUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RKw6UkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RK0ksEXPEfCMIvdXAFdhzA" target="_RB4EEEXPEfCMIvdXAFdhzA" source="_RCKX8EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RK1LwEXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RK1LwUXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RK42IEXPEfCMIvdXAFdhzA" target="_RCXzUEXPEfCMIvdXAFdhzA" source="_RCS60EXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RK5dMEXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RK5dMUXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RK9uoEXPEfCMIvdXAFdhzA" target="_RB4EEEXPEfCMIvdXAFdhzA" source="_RCqHMEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RK9uoUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RK9uokXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RLCnIEXPEfCMIvdXAFdhzA" target="_RBb_MEXPEfCMIvdXAFdhzA" source="_RCu_sEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RLCnIUXPEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_RLCnIkXPEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_fbYuBEXUEfCMIvdXAFdhzA" target="_fbYG8EXUEfCMIvdXAFdhzA" source="_RCcEwEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_fbYuBUXUEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_fbYuBkXUEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_hRAy4EXUEfCMIvdXAFdhzA" target="_RCcEwEXPEfCMIvdXAFdhzA" source="_eAvU8EXUEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_hRAy4UXUEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_hRAy4kXUEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ibbXkEXUEfCMIvdXAFdhzA" target="_Q_fecEXPEfCMIvdXAFdhzA" source="_h2znkEXUEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ibbXkUXUEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_ibbXkkXUEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_udW4YEXUEfCMIvdXAFdhzA" target="_c_y1UEXUEfCMIvdXAFdhzA" source="_Q_qdkEXPEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_udW4YUXUEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_udW4YkXUEfCMIvdXAFdhzA" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_O9Y1EEXVEfCMIvdXAFdhzA" target="_RAVL8EXPEfCMIvdXAFdhzA" source="_LSZKAEXVEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_O9Y1EUXVEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_O9Y1EkXVEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_WE8GkEXVEfCMIvdXAFdhzA" target="_RALa8EXPEfCMIvdXAFdhzA" source="_TWgKYEXVEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_WE8GkUXVEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_WE8GkkXVEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_iPTxsEXVEfCMIvdXAFdhzA" target="_RCS60EXPEfCMIvdXAFdhzA" source="_hgXBAEXVEfCMIvdXAFdhzA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_iPTxsUXVEfCMIvdXAFdhzA"/>
        <condition xmi:type="expression:Expression" xmi:id="_iPTxskXVEfCMIvdXAFdhzA" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <contract xmi:type="process:Contract" xmi:id="_Q-9TBEXPEfCMIvdXAFdhzA"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-9S8UXPEfCMIvdXAFdhzA">
        <name xmi:type="expression:Expression" xmi:id="_Q-9S8kXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-9S80XPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-9S9EXPEfCMIvdXAFdhzA">
        <name xmi:type="expression:Expression" xmi:id="_Q-9S9UXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-9S9kXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-9S90XPEfCMIvdXAFdhzA">
        <name xmi:type="expression:Expression" xmi:id="_Q-9S-EXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-9S-UXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-9S-kXPEfCMIvdXAFdhzA">
        <name xmi:type="expression:Expression" xmi:id="_Q-9S-0XPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-9S_EXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Q-9S_UXPEfCMIvdXAFdhzA">
        <name xmi:type="expression:Expression" xmi:id="_Q-9S_kXPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Q-9S_0XPEfCMIvdXAFdhzA" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_QxhT4EXPEfCMIvdXAFdhzA" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_QxhT4UXPEfCMIvdXAFdhzA" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_QxhT4kXPEfCMIvdXAFdhzA" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_QxhT40XPEfCMIvdXAFdhzA" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_QxhT5EXPEfCMIvdXAFdhzA" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_QxhT5UXPEfCMIvdXAFdhzA" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_QxhT5kXPEfCMIvdXAFdhzA" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_QxhT50XPEfCMIvdXAFdhzA" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_QxhT6EXPEfCMIvdXAFdhzA" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_QxdpgEXPEfCMIvdXAFdhzA" type="Process" element="_QxbNQEXPEfCMIvdXAFdhzA" name="Definitions_1" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Q-96AEXPEfCMIvdXAFdhzA" type="2007" element="_Q-9S8EXPEfCMIvdXAFdhzA">
      <children xmi:type="notation:DecorationNode" xmi:id="_Q-96BUXPEfCMIvdXAFdhzA" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Q-96BkXPEfCMIvdXAFdhzA" type="7001">
        <children xmi:type="notation:Shape" xmi:id="_Q_L8dkXPEfCMIvdXAFdhzA" type="3027" element="_Q_LVYEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_L8eEXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_L8d0XPEfCMIvdXAFdhzA" x="190" y="155" width="142" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q_SDEEXPEfCMIvdXAFdhzA" type="3012" element="_Q_Q08EXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_SDEkXPEfCMIvdXAFdhzA" type="5029">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Q_SDE0XPEfCMIvdXAFdhzA" x="-1" y="-59"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_SDEUXPEfCMIvdXAFdhzA" x="102" y="177"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q_gFhkXPEfCMIvdXAFdhzA" type="3027" element="_Q_fecEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_gFiEXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_gFh0XPEfCMIvdXAFdhzA" x="740" y="283" width="131" height="64"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q_rEoEXPEfCMIvdXAFdhzA" type="3025" element="_Q_qdkEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_rEokXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_rEoUXPEfCMIvdXAFdhzA" x="350" y="155" width="150" height="75"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q_vWEEXPEfCMIvdXAFdhzA" type="3062" element="_Q_uvAEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_vWEkXPEfCMIvdXAFdhzA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Q_vWE0XPEfCMIvdXAFdhzA" x="-7" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_vWEUXPEfCMIvdXAFdhzA" x="984" y="287"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_Q_8KY0XPEfCMIvdXAFdhzA" type="3008" element="_Q_7jUEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_Q_8xcEXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_Q_8xcUXPEfCMIvdXAFdhzA" x="-16" y="-51"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q_8KZEXPEfCMIvdXAFdhzA" x="2045" y="170"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAAb2UXPEfCMIvdXAFdhzA" type="3025" element="_RAAb0EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RABC4EXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAAb2kXPEfCMIvdXAFdhzA" x="1414" y="155" width="149" height="74"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAFUU0XPEfCMIvdXAFdhzA" type="3062" element="_RAEtQEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAFUVUXPEfCMIvdXAFdhzA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RAFUVkXPEfCMIvdXAFdhzA" x="-8" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAFUVEXPEfCMIvdXAFdhzA" x="2332" y="427"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAMCAEXPEfCMIvdXAFdhzA" type="3027" element="_RALa8EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAMCAkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAMCAUXPEfCMIvdXAFdhzA" x="2070" y="405"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAQ6gEXPEfCMIvdXAFdhzA" type="3003" element="_RAQTcEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAQ6gkXPEfCMIvdXAFdhzA" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RAQ6g0XPEfCMIvdXAFdhzA" x="-9" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAQ6gUXPEfCMIvdXAFdhzA" x="2332" y="527"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAVzCEXPEfCMIvdXAFdhzA" type="3025" element="_RAVL8EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAVzCkXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAVzCUXPEfCMIvdXAFdhzA" x="1901" y="505"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAZdYEXPEfCMIvdXAFdhzA" type="3026" element="_RAY2UEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAZdYkXPEfCMIvdXAFdhzA" type="5012"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAZdYUXPEfCMIvdXAFdhzA" x="1604" y="155" width="156" height="78"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAe88EXPEfCMIvdXAFdhzA" type="3005" element="_RAeV4EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAe88kXPEfCMIvdXAFdhzA" type="5005"/>
          <children xmi:type="notation:Shape" xmi:id="_hgXBAUXVEfCMIvdXAFdhzA" type="3029" element="_hgXBAEXVEfCMIvdXAFdhzA" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_hgXoEEXVEfCMIvdXAFdhzA" type="5053">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_hgXoEUXVEfCMIvdXAFdhzA" y="29"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hgXBAkXVEfCMIvdXAFdhzA"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAe88UXPEfCMIvdXAFdhzA" x="1800" y="155"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAj1cEXPEfCMIvdXAFdhzA" type="3005" element="_RAjOYEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAj1ckXPEfCMIvdXAFdhzA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAj1cUXPEfCMIvdXAFdhzA" x="2117" y="155" width="142" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RApVAEXPEfCMIvdXAFdhzA" type="3027" element="_RAot8EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RApVAkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RApVAUXPEfCMIvdXAFdhzA" x="2297" y="155" width="148" height="74"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAuNgEXPEfCMIvdXAFdhzA" type="3005" element="_RAtmcEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAuNgkXPEfCMIvdXAFdhzA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAuNgUXPEfCMIvdXAFdhzA" x="2470" y="155" width="142" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RAx340XPEfCMIvdXAFdhzA" type="3008" element="_RAxQ0EXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RAx35UXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RAx35kXPEfCMIvdXAFdhzA" x="-20" y="-54"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RAx35EXPEfCMIvdXAFdhzA" x="2664" y="164"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RA2wYEXPEfCMIvdXAFdhzA" type="3027" element="_RA2JUEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RA2wYkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RA2wYUXPEfCMIvdXAFdhzA" x="2820" y="155" width="135" height="67"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RA7B00XPEfCMIvdXAFdhzA" type="3008" element="_RA6awEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RA7B1UXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RA7B1kXPEfCMIvdXAFdhzA" x="-16" y="-60"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RA7B1EXPEfCMIvdXAFdhzA" x="3033" y="170"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RA_TQ0XPEfCMIvdXAFdhzA" type="3008" element="_RA-sMEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RA_TRUXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RA_TRkXPEfCMIvdXAFdhzA" x="-30" y="-59"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RA_TREXPEfCMIvdXAFdhzA" x="3325" y="170"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBELxEXPEfCMIvdXAFdhzA" type="3025" element="_RBDksEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBELxkXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBELxUXPEfCMIvdXAFdhzA" x="822" y="155" width="148" height="74"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBH2KUXPEfCMIvdXAFdhzA" type="3026" element="_RBH2IEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBIdMEXPEfCMIvdXAFdhzA" type="5012"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBH2KkXPEfCMIvdXAFdhzA" x="1015" y="159" width="128" height="64"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBMHk0XPEfCMIvdXAFdhzA" type="3008" element="_RBLggEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBMuoEXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBMuoUXPEfCMIvdXAFdhzA" x="-7" y="-73"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBMHlEXPEfCMIvdXAFdhzA" x="1205" y="170"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBQZCEXPEfCMIvdXAFdhzA" type="3027" element="_RBPx8EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBQZCkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBQZCUXPEfCMIvdXAFdhzA" x="3105" y="155" width="162" height="81"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBUqc0XPEfCMIvdXAFdhzA" type="3008" element="_RBUDYEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBUqdUXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBUqdkXPEfCMIvdXAFdhzA" x="-4" y="-67"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBUqdEXPEfCMIvdXAFdhzA" x="4596" y="230"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBY74EXPEfCMIvdXAFdhzA" type="3003" element="_RBYU0EXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBY74kXPEfCMIvdXAFdhzA" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBY740XPEfCMIvdXAFdhzA" x="-8" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBY74UXPEfCMIvdXAFdhzA" x="5202" y="237"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBcmQ0XPEfCMIvdXAFdhzA" type="3008" element="_RBb_MEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBcmRUXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBcmRkXPEfCMIvdXAFdhzA" y="-67"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBcmREXPEfCMIvdXAFdhzA" x="4995" y="230"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBiF0EXPEfCMIvdXAFdhzA" type="3009" element="_RBhewEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBiF0kXPEfCMIvdXAFdhzA" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBiF00XPEfCMIvdXAFdhzA" x="-12" y="-60"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBiF0UXPEfCMIvdXAFdhzA" x="3455" y="390"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBsd40XPEfCMIvdXAFdhzA" type="3009" element="_RBr20EXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBsd5UXPEfCMIvdXAFdhzA" type="5020">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RBsd5kXPEfCMIvdXAFdhzA" x="28" y="-63"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBsd5EXPEfCMIvdXAFdhzA" x="3725" y="390"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RBwvUEXPEfCMIvdXAFdhzA" type="3027" element="_RBwIQEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RBwvUkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RBwvUUXPEfCMIvdXAFdhzA" x="3660" y="45" width="192" height="96"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RB1AwEXPEfCMIvdXAFdhzA" type="3027" element="_RB0ZsEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RB1AwkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RB1AwUXPEfCMIvdXAFdhzA" x="3660" y="215" width="140" height="70"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RB4rI0XPEfCMIvdXAFdhzA" type="3008" element="_RB4EEEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RB4rJUXPEfCMIvdXAFdhzA" type="5026">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RB4rJkXPEfCMIvdXAFdhzA" x="29" y="46"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RB4rJEXPEfCMIvdXAFdhzA" x="4265" y="230"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RB88k0XPEfCMIvdXAFdhzA" type="3062" element="_RB8VgEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RB88lUXPEfCMIvdXAFdhzA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RB88lkXPEfCMIvdXAFdhzA" x="8" y="16"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RB88lEXPEfCMIvdXAFdhzA" x="4612" y="357"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCB1EEXPEfCMIvdXAFdhzA" type="3062" element="_RCBOAEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCB1EkXPEfCMIvdXAFdhzA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RCB1E0XPEfCMIvdXAFdhzA" x="-21" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCB1EUXPEfCMIvdXAFdhzA" x="5202" y="347"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCGtkEXPEfCMIvdXAFdhzA" type="3027" element="_RCFfcEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCGtkkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCGtkUXPEfCMIvdXAFdhzA" x="3560" y="375" width="128" height="64"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCK_AEXPEfCMIvdXAFdhzA" type="3026" element="_RCKX8EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCK_AkXPEfCMIvdXAFdhzA" type="5012"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCK_AUXPEfCMIvdXAFdhzA" x="3900" y="375" width="148" height="74"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCPQeEXPEfCMIvdXAFdhzA" type="3025" element="_RCOpYEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCP3gEXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCPQeUXPEfCMIvdXAFdhzA" x="3560" y="505" width="145" height="72"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCTh6EXPEfCMIvdXAFdhzA" type="3025" element="_RCS60EXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCUI8EXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCTh6UXPEfCMIvdXAFdhzA" x="1780" y="345"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCYaYEXPEfCMIvdXAFdhzA" type="3062" element="_RCXzUEXPEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCYaYkXPEfCMIvdXAFdhzA" type="5090">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_RCYaY0XPEfCMIvdXAFdhzA" x="-21" y="13"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCYaYUXPEfCMIvdXAFdhzA" x="1832" y="547"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCcr2EXPEfCMIvdXAFdhzA" type="3025" element="_RCcEwEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCcr2kXPEfCMIvdXAFdhzA" type="5011"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCcr2UXPEfCMIvdXAFdhzA" x="735" y="394" width="142" height="71"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RChkUEXPEfCMIvdXAFdhzA" type="3027" element="_RCg9QEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RChkUkXPEfCMIvdXAFdhzA" type="5017"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RChkUUXPEfCMIvdXAFdhzA" x="4367" y="215"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCmc3EXPEfCMIvdXAFdhzA" type="3005" element="_RCl1wEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCmc3kXPEfCMIvdXAFdhzA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCmc3UXPEfCMIvdXAFdhzA" x="3940" y="215" width="134" height="67"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCrVUEXPEfCMIvdXAFdhzA" type="3005" element="_RCqHMEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCrVUkXPEfCMIvdXAFdhzA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCrVUUXPEfCMIvdXAFdhzA" x="3950" y="45" width="162" height="81"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_RCvmwEXPEfCMIvdXAFdhzA" type="3005" element="_RCu_sEXPEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_RCvmwkXPEfCMIvdXAFdhzA" type="5005"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_RCvmwUXPEfCMIvdXAFdhzA" x="4760" y="215"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_c_zcYEXUEfCMIvdXAFdhzA" type="3005" element="_c_y1UEXUEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_c_zcYkXUEfCMIvdXAFdhzA" type="5005"/>
          <children xmi:type="notation:Shape" xmi:id="_eAvU8UXUEfCMIvdXAFdhzA" type="3064" element="_eAvU8EXUEfCMIvdXAFdhzA" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_eAvU80XUEfCMIvdXAFdhzA" type="5094">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_eAvU9EXUEfCMIvdXAFdhzA" y="5"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eAvU8kXUEfCMIvdXAFdhzA" y="52"/>
          </children>
          <children xmi:type="notation:Shape" xmi:id="_h20OoEXUEfCMIvdXAFdhzA" type="3043" element="_h2znkEXUEfCMIvdXAFdhzA" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_h20OokXUEfCMIvdXAFdhzA" type="5055">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_h20Oo0XUEfCMIvdXAFdhzA" y="5"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_h20OoUXUEfCMIvdXAFdhzA" x="76" y="52"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_c_zcYUXUEfCMIvdXAFdhzA" x="597" y="163" width="120" height="60"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_fbYuAEXUEfCMIvdXAFdhzA" type="3003" element="_fbYG8EXUEfCMIvdXAFdhzA" fontName="Segoe UI">
          <children xmi:type="notation:DecorationNode" xmi:id="_fbYuAkXUEfCMIvdXAFdhzA" type="5025">
            <layoutConstraint xmi:type="notation:Location" xmi:id="_fbYuA0XUEfCMIvdXAFdhzA" y="5"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fbYuAUXUEfCMIvdXAFdhzA" x="969" y="413"/>
        </children>
        <children xmi:type="notation:Shape" xmi:id="_CXWhrEXVEfCMIvdXAFdhzA" type="3005" element="_CXV6kEXVEfCMIvdXAFdhzA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
          <children xmi:type="notation:DecorationNode" xmi:id="_CXWhrkXVEfCMIvdXAFdhzA" type="5005"/>
          <children xmi:type="notation:Shape" xmi:id="_LSZxEEXVEfCMIvdXAFdhzA" type="3064" element="_LSZKAEXVEfCMIvdXAFdhzA" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_LSaYIEXVEfCMIvdXAFdhzA" type="5094">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_LSaYIUXVEfCMIvdXAFdhzA" y="60"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LSZxEUXVEfCMIvdXAFdhzA" x="8" y="42"/>
          </children>
          <children xmi:type="notation:Shape" xmi:id="_TWgxcEXVEfCMIvdXAFdhzA" type="3043" element="_TWgKYEXVEfCMIvdXAFdhzA" fontName="Segoe UI">
            <children xmi:type="notation:DecorationNode" xmi:id="_TWgxckXVEfCMIvdXAFdhzA" type="5055">
              <layoutConstraint xmi:type="notation:Location" xmi:id="_TWgxc0XVEfCMIvdXAFdhzA" y="5"/>
            </children>
            <layoutConstraint xmi:type="notation:Bounds" xmi:id="_TWgxcUXVEfCMIvdXAFdhzA" x="75" y="42"/>
          </children>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CXWhrUXVEfCMIvdXAFdhzA" x="1930" y="285" width="100" height="50"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Q-96AUXPEfCMIvdXAFdhzA"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Q-96AkXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Q-96A0XPEfCMIvdXAFdhzA" lineColor="12632256"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Q-96B0XPEfCMIvdXAFdhzA"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Q-96BEXPEfCMIvdXAFdhzA" width="5373" height="775"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_QxdpgUXPEfCMIvdXAFdhzA"/>
    <edges xmi:type="notation:Connector" xmi:id="_RH3XUkXPEfCMIvdXAFdhzA" type="4001" element="_RH2wQEXPEfCMIvdXAFdhzA" source="_Q_SDEEXPEfCMIvdXAFdhzA" target="_Q_L8dkXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RH3XVUXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RH3XVkXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RH3XU0XPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RH3XVEXPEfCMIvdXAFdhzA" points="[0, 0, -52, 0]$[52, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RH8P00XPEfCMIvdXAFdhzA" type="4001" element="_RH8P0EXPEfCMIvdXAFdhzA" source="_Q_L8dkXPEfCMIvdXAFdhzA" target="_Q_rEoEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RH8P1kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RH8P10XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RH8P1EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RH8P1UXPEfCMIvdXAFdhzA" points="[0, 0, -60, 0]$[60, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIFZw0XPEfCMIvdXAFdhzA" type="4001" element="_RIFZwEXPEfCMIvdXAFdhzA" source="_Q_gFhkXPEfCMIvdXAFdhzA" target="_Q_vWEEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIFZxkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIFZx0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIFZxEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIFZxUXPEfCMIvdXAFdhzA" points="[0, 0, -52, 0]$[52, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIV4c0XPEfCMIvdXAFdhzA" type="4001" element="_RIV4cEXPEfCMIvdXAFdhzA" source="_RBELxEXPEfCMIvdXAFdhzA" target="_RBH2KUXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIV4dkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIV4d0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIV4dEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIV4dUXPEfCMIvdXAFdhzA" points="[0, 0, -70, 0]$[70, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIaJ40XPEfCMIvdXAFdhzA" type="4001" element="_RIaJ4EXPEfCMIvdXAFdhzA" source="_RBH2KUXPEfCMIvdXAFdhzA" target="_RBMHk0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIaJ5kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIaJ50XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIaJ5EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIaJ5UXPEfCMIvdXAFdhzA" points="[0, 0, -65, 0]$[65, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIebUEXPEfCMIvdXAFdhzA" type="4001" element="_RId0QEXPEfCMIvdXAFdhzA" source="_RBMHk0XPEfCMIvdXAFdhzA" target="_CXWhrEXVEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIebU0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIebVEXPEfCMIvdXAFdhzA" x="-6" y="6"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIebUUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIebUkXPEfCMIvdXAFdhzA" points="[0, 0, -700, -105]$[0, 105, -700, 0]$[700, 105, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIisw0XPEfCMIvdXAFdhzA" type="4001" element="_RIiswEXPEfCMIvdXAFdhzA" source="_RBMHk0XPEfCMIvdXAFdhzA" target="_RAAb2UXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIisxkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIisx0XPEfCMIvdXAFdhzA" x="-65" y="8"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIisxEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIisxUXPEfCMIvdXAFdhzA" points="[0, 0, -255, 0]$[255, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIm-MEXPEfCMIvdXAFdhzA" type="4001" element="_RImXIEXPEfCMIvdXAFdhzA" source="_CXWhrEXVEfCMIvdXAFdhzA" target="_Q_8KY0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIm-M0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIm-NEXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIm-MUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIm-MkXPEfCMIvdXAFdhzA" points="[0, 0, -40, 105]$[40, 0, 0, 105]$[40, -105, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIqok0XPEfCMIvdXAFdhzA" type="4001" element="_RIqokEXPEfCMIvdXAFdhzA" source="_RAe88EXPEfCMIvdXAFdhzA" target="_Q_8KY0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIqolkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIqol0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIqolEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIqolUXPEfCMIvdXAFdhzA" points="[0, 0, -145, 0]$[145, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIuS80XPEfCMIvdXAFdhzA" type="4001" element="_RIuS8EXPEfCMIvdXAFdhzA" source="_Q_8KY0XPEfCMIvdXAFdhzA" target="_RAj1cEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIu6AEXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIu6AUXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIuS9EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIuS9UXPEfCMIvdXAFdhzA" points="[0, 0, -115, 0]$[115, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RIykY0XPEfCMIvdXAFdhzA" type="4001" element="_RIykYEXPEfCMIvdXAFdhzA" source="_RAAb2UXPEfCMIvdXAFdhzA" target="_RAZdYEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RIykZkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RIykZ0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RIykZEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RIykZUXPEfCMIvdXAFdhzA" points="[0, 0, -50, 0]$[50, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RI210EXPEfCMIvdXAFdhzA" type="4001" element="_RI2OwEXPEfCMIvdXAFdhzA" source="_RAMCAEXPEfCMIvdXAFdhzA" target="_RAFUU0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RI2100XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RI211EXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RI210UXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RI210kXPEfCMIvdXAFdhzA" points="[0, 0, -162, 0]$[162, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RI-xo0XPEfCMIvdXAFdhzA" type="4001" element="_RI-xoEXPEfCMIvdXAFdhzA" source="_RAVzCEXPEfCMIvdXAFdhzA" target="_RAQ6gEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RI-xpkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RI-xp0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RI-xpEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RI-xpUXPEfCMIvdXAFdhzA" points="[0, 0, -192, 0]$[192, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJGtc0XPEfCMIvdXAFdhzA" type="4001" element="_RJGtcEXPEfCMIvdXAFdhzA" source="_RAZdYEXPEfCMIvdXAFdhzA" target="_RAe88EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJHUgEXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJHUgUXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJGtdEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJGtdUXPEfCMIvdXAFdhzA" points="[0, 0, -40, 0]$[40, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJK-40XPEfCMIvdXAFdhzA" type="4001" element="_RJK-4EXPEfCMIvdXAFdhzA" source="_RAj1cEXPEfCMIvdXAFdhzA" target="_RApVAEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJK-5kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJK-50XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJK-5EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJK-5UXPEfCMIvdXAFdhzA" points="[0, 0, -30, 0]$[30, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJOpQ0XPEfCMIvdXAFdhzA" type="4001" element="_RJOpQEXPEfCMIvdXAFdhzA" source="_RApVAEXPEfCMIvdXAFdhzA" target="_RAuNgEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJOpRkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJOpR0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJOpREXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJOpRUXPEfCMIvdXAFdhzA" points="[0, 0, -30, 0]$[30, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJSTo0XPEfCMIvdXAFdhzA" type="4001" element="_RJSToEXPEfCMIvdXAFdhzA" source="_RAuNgEXPEfCMIvdXAFdhzA" target="_RAx340XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJS6sEXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJS6sUXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJSTpEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJSTpUXPEfCMIvdXAFdhzA" points="[0, 0, -45, 0]$[45, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJWlE0XPEfCMIvdXAFdhzA" type="4001" element="_RJWlEEXPEfCMIvdXAFdhzA" source="_RAx340XPEfCMIvdXAFdhzA" target="_RA2wYEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJWlFkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJWlF0XPEfCMIvdXAFdhzA" x="-4" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJWlFEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJWlFUXPEfCMIvdXAFdhzA" points="[0, 0, -155, 0]$[155, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJa2g0XPEfCMIvdXAFdhzA" type="4001" element="_RJa2gEXPEfCMIvdXAFdhzA" source="_RAx340XPEfCMIvdXAFdhzA" target="_RA7B00XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJa2hkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJa2h0XPEfCMIvdXAFdhzA" x="-10" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJa2hEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJa2hUXPEfCMIvdXAFdhzA" points="[0, 0, -460, 0]$[0, 105, -460, 105]$[460, 105, 0, 105]$[460, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_xGu48EXVEfCMIvdXAFdhzA" id="(0.7674418604651163,0.5581395348837209)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJfH80XPEfCMIvdXAFdhzA" type="4001" element="_RJfH8EXPEfCMIvdXAFdhzA" source="_RA2wYEXPEfCMIvdXAFdhzA" target="_RA7B00XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJfH9kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJfH90XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJfH9EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJfH9UXPEfCMIvdXAFdhzA" points="[0, 0, -155, 0]$[155, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJjZYEXPEfCMIvdXAFdhzA" type="4001" element="_RJiyUEXPEfCMIvdXAFdhzA" source="_RA7B00XPEfCMIvdXAFdhzA" target="_RBQZCEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJjZY0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJjZZEXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJjZYUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJjZYkXPEfCMIvdXAFdhzA" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJnDw0XPEfCMIvdXAFdhzA" type="4001" element="_RJnDwEXPEfCMIvdXAFdhzA" source="_RBQZCEXPEfCMIvdXAFdhzA" target="_RA_TQ0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJnDxkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJnDx0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJnDxEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJnDxUXPEfCMIvdXAFdhzA" points="[0, 0, -45, 0]$[45, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJrVMEXPEfCMIvdXAFdhzA" type="4001" element="_RJquIEXPEfCMIvdXAFdhzA" source="_c_zcYEXUEfCMIvdXAFdhzA" target="_RBELxEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJrVM0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJrVNEXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJrVMUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJrVMkXPEfCMIvdXAFdhzA" points="[0, 0, -260, 0]$[260, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJu_k0XPEfCMIvdXAFdhzA" type="4001" element="_RJu_kEXPEfCMIvdXAFdhzA" source="_RA_TQ0XPEfCMIvdXAFdhzA" target="_RBiF0EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJvmoEXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJvmoUXPEfCMIvdXAFdhzA" x="-17" y="-8"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJu_lEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJu_lUXPEfCMIvdXAFdhzA" points="[0, 0, -105, -195]$[0, 195, -105, 0]$[105, 195, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJz4EEXPEfCMIvdXAFdhzA" type="4001" element="_RJzRAEXPEfCMIvdXAFdhzA" source="_RA_TQ0XPEfCMIvdXAFdhzA" target="_RBwvUEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJz4E0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJz4FEXPEfCMIvdXAFdhzA" x="-31" y="-17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJz4EUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJz4EkXPEfCMIvdXAFdhzA" points="[0, 0, -310, 85]$[0, -85, -310, 0]$[310, -85, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJ3ic0XPEfCMIvdXAFdhzA" type="4001" element="_RJ3icEXPEfCMIvdXAFdhzA" source="_RChkUEXPEfCMIvdXAFdhzA" target="_RBUqc0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJ3idkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJ3id0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJ3idEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJ3idUXPEfCMIvdXAFdhzA" points="[0, 0, -65, 0]$[65, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJ7M00XPEfCMIvdXAFdhzA" type="4001" element="_RJ7M0EXPEfCMIvdXAFdhzA" source="_RBUqc0XPEfCMIvdXAFdhzA" target="_RB88k0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJ7M1kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJ7M10XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJ7M1EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJ7M1UXPEfCMIvdXAFdhzA" points="[0, 0, -32, -95]$[0, 95, -32, 0]$[32, 95, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RJ-3M0XPEfCMIvdXAFdhzA" type="4001" element="_RJ-3MEXPEfCMIvdXAFdhzA" source="_RBUqc0XPEfCMIvdXAFdhzA" target="_RCvmwEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RJ_eQEXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RJ_eQUXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RJ-3NEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RJ-3NUXPEfCMIvdXAFdhzA" points="[0, 0, -155, 0]$[155, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKDIo0XPEfCMIvdXAFdhzA" type="4001" element="_RKDIoEXPEfCMIvdXAFdhzA" source="_RBcmQ0XPEfCMIvdXAFdhzA" target="_RBY74EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKDIpkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKDIp0XPEfCMIvdXAFdhzA" x="-9" y="-18"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKDIpEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKDIpUXPEfCMIvdXAFdhzA" points="[0, 0, -157, 0]$[157, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKIBIEXPEfCMIvdXAFdhzA" type="4001" element="_RKHaEEXPEfCMIvdXAFdhzA" source="_RBcmQ0XPEfCMIvdXAFdhzA" target="_RCB1EEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKIBI0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKIBJEXPEfCMIvdXAFdhzA" x="-43" y="-45"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKIBIUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKIBIkXPEfCMIvdXAFdhzA" points="[0, 0, -182, -85]$[0, 85, -182, 0]$[182, 85, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKMSkkXPEfCMIvdXAFdhzA" type="4001" element="_RKLrgEXPEfCMIvdXAFdhzA" source="_RBsd40XPEfCMIvdXAFdhzA" target="_RCK_AEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKMSlUXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKMSlkXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKMSk0XPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKMSlEXPEfCMIvdXAFdhzA" points="[0, 0, -125, 0]$[125, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKP880XPEfCMIvdXAFdhzA" type="4001" element="_RKP88EXPEfCMIvdXAFdhzA" source="_RBiF0EXPEfCMIvdXAFdhzA" target="_RCPQeEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKP89kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKP890XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKP89EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKP89UXPEfCMIvdXAFdhzA" points="[0, 0, -80, -105]$[0, 105, -80, 0]$[80, 105, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKUOYkXPEfCMIvdXAFdhzA" type="4001" element="_RKTnUEXPEfCMIvdXAFdhzA" source="_RBiF0EXPEfCMIvdXAFdhzA" target="_RCGtkEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKUOZUXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKUOZkXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKUOY0XPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKUOZEXPEfCMIvdXAFdhzA" points="[0, 0, -55, 0]$[55, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKYf00XPEfCMIvdXAFdhzA" type="4001" element="_RKYf0EXPEfCMIvdXAFdhzA" source="_RCPQeEXPEfCMIvdXAFdhzA" target="_RBsd40XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKYf1kXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKYf10XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKYf1EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKYf1UXPEfCMIvdXAFdhzA" points="[0, 0, -90, 105]$[90, 0, 0, 105]$[90, -105, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKcxQ0XPEfCMIvdXAFdhzA" type="4001" element="_RKcxQEXPEfCMIvdXAFdhzA" source="_RCGtkEXPEfCMIvdXAFdhzA" target="_RBsd40XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKcxRkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKcxR0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKcxREXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKcxRUXPEfCMIvdXAFdhzA" points="[0, 0, -65, 0]$[65, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKgbo0XPEfCMIvdXAFdhzA" type="4001" element="_RKgboEXPEfCMIvdXAFdhzA" source="_RBwvUEXPEfCMIvdXAFdhzA" target="_RCrVUEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKhCskXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKhCs0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKhCsEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKhCsUXPEfCMIvdXAFdhzA" points="[0, 0, -190, 0]$[190, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKktE0XPEfCMIvdXAFdhzA" type="4001" element="_RKktEEXPEfCMIvdXAFdhzA" source="_RB1AwEXPEfCMIvdXAFdhzA" target="_RCmc3EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKktFkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKktF0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKktFEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKktFUXPEfCMIvdXAFdhzA" points="[0, 0, -180, 0]$[180, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKoXc0XPEfCMIvdXAFdhzA" type="4001" element="_RKoXcEXPEfCMIvdXAFdhzA" source="_RA_TQ0XPEfCMIvdXAFdhzA" target="_RB1AwEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKoXdkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKoXd0XPEfCMIvdXAFdhzA" x="-17" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKoXdEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKoXdUXPEfCMIvdXAFdhzA" points="[0, 0, -285, -60]$[145, 0, -140, -60]$[145, 60, -140, 0]$[285, 60, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKso40XPEfCMIvdXAFdhzA" type="4001" element="_RKso4EXPEfCMIvdXAFdhzA" source="_RCmc3EXPEfCMIvdXAFdhzA" target="_RB4rI0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKtP8EXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKtP8UXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKso5EXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKso5UXPEfCMIvdXAFdhzA" points="[0, 0, -225, 0]$[225, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RKw6U0XPEfCMIvdXAFdhzA" type="4001" element="_RKw6UEXPEfCMIvdXAFdhzA" source="_RB4rI0XPEfCMIvdXAFdhzA" target="_RChkUEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RKw6VkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RKw6V0XPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RKw6VEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RKw6VUXPEfCMIvdXAFdhzA" points="[0, 0, -75, 0]$[75, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RK1LwkXPEfCMIvdXAFdhzA" type="4001" element="_RK0ksEXPEfCMIvdXAFdhzA" source="_RCK_AEXPEfCMIvdXAFdhzA" target="_RB4rI0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RK1LxUXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RK1LxkXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RK1Lw0XPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RK1LxEXPEfCMIvdXAFdhzA" points="[0, 0, -290, 135]$[290, 0, 0, 135]$[290, -135, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RK5dMkXPEfCMIvdXAFdhzA" type="4001" element="_RK42IEXPEfCMIvdXAFdhzA" source="_RCTh6EXPEfCMIvdXAFdhzA" target="_RCYaYEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RK5dNUXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RK5dNkXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RK5dM0XPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RK5dNEXPEfCMIvdXAFdhzA" points="[0, 0, -20, -122]$[0, 61, -20, -61]$[20, 61, 0, -61]$[20, 122, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RK9uo0XPEfCMIvdXAFdhzA" type="4001" element="_RK9uoEXPEfCMIvdXAFdhzA" source="_RCrVUEXPEfCMIvdXAFdhzA" target="_RB4rI0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RK9upkXPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RK-VsEXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RK9upEXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RK9upUXPEfCMIvdXAFdhzA" points="[0, 0, -240, -145]$[240, 0, 0, -145]$[240, 145, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RLDOMEXPEfCMIvdXAFdhzA" type="4001" element="_RLCnIEXPEfCMIvdXAFdhzA" source="_RCvmwEXPEfCMIvdXAFdhzA" target="_RBcmQ0XPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear" lineColor="12632256">
      <children xmi:type="notation:DecorationNode" xmi:id="_RLDOM0XPEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RLDONEXPEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RLDOMUXPEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RLDOMkXPEfCMIvdXAFdhzA" points="[0, 0, -135, 0]$[135, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_fbYuB0XUEfCMIvdXAFdhzA" type="4001" element="_fbYuBEXUEfCMIvdXAFdhzA" source="_RCcr2EXPEfCMIvdXAFdhzA" target="_fbYuAEXUEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_fbYuCkXUEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_fbYuC0XUEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_fbYuCEXUEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_fbYuCUXUEfCMIvdXAFdhzA" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_hRBZ8EXUEfCMIvdXAFdhzA" type="4001" element="_hRAy4EXUEfCMIvdXAFdhzA" source="_eAvU8UXUEfCMIvdXAFdhzA" target="_RCcr2EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_hRBZ80XUEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_hRBZ9EXUEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_hRBZ8UXUEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_hRBZ8kXUEfCMIvdXAFdhzA" points="[0, 0, -99, -191]$[93, 191, -6, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hRCBAEXUEfCMIvdXAFdhzA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_hRCBAUXUEfCMIvdXAFdhzA" id="(0.04225352112676056,0.5211267605633803)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ibbXk0XUEfCMIvdXAFdhzA" type="4001" element="_ibbXkEXUEfCMIvdXAFdhzA" source="_h20OoEXUEfCMIvdXAFdhzA" target="_Q_gFhkXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ibbXlkXUEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ibbXl0XUEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ibbXlEXUEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ibbXlUXUEfCMIvdXAFdhzA" points="[0, 0, -73, -76]$[65, 76, -8, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ibb-oEXUEfCMIvdXAFdhzA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ibb-oUXUEfCMIvdXAFdhzA" id="(0.061068702290076333,0.515625)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_udW4Y0XUEfCMIvdXAFdhzA" type="4001" element="_udW4YEXUEfCMIvdXAFdhzA" source="_Q_rEoEXPEfCMIvdXAFdhzA" target="_c_zcYEXUEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_udW4ZkXUEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_udW4Z0XUEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_udW4ZEXUEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_udW4ZUXUEfCMIvdXAFdhzA" points="[0, 0, -106, -11]$[97, 10, -9, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_udXfcEXUEfCMIvdXAFdhzA" id="(1.0,0.32)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_udXfcUXUEfCMIvdXAFdhzA" id="(0.075,0.45)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_O9Y1E0XVEfCMIvdXAFdhzA" type="4001" element="_O9Y1EEXVEfCMIvdXAFdhzA" source="_LSZxEEXVEfCMIvdXAFdhzA" target="_RAVzCEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_O9Y1FkXVEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_O9Y1F0XVEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_O9Y1FEXVEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_O9Y1FUXVEfCMIvdXAFdhzA" points="[-6, 0, 14, -178]$[-6, 61, 14, -117]$[-17, 61, 3, -117]$[-17, 153, 3, -25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_O9ZcIEXVEfCMIvdXAFdhzA" id="(1.0,1.0)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_WE8Gk0XVEfCMIvdXAFdhzA" type="4001" element="_WE8GkEXVEfCMIvdXAFdhzA" source="_TWgxcEXVEfCMIvdXAFdhzA" target="_RAMCAEXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_WE8toEXVEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_WE8toUXVEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_WE8GlEXVEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_WE8GlUXVEfCMIvdXAFdhzA" points="[0, 0, -41, -81]$[40, 81, -1, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WE8tokXVEfCMIvdXAFdhzA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_WE8to0XVEfCMIvdXAFdhzA" id="(0.01,0.56)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_iPTxs0XVEfCMIvdXAFdhzA" type="4001" element="_iPTxsEXVEfCMIvdXAFdhzA" source="_hgXBAUXVEfCMIvdXAFdhzA" target="_RCTh6EXPEfCMIvdXAFdhzA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_iPUYwkXVEfCMIvdXAFdhzA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_iPUYw0XVEfCMIvdXAFdhzA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_iPUYwEXVEfCMIvdXAFdhzA" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_iPUYwUXVEfCMIvdXAFdhzA" points="[-7, -3, 0, -133]$[-6, 123, 1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iPU_0EXVEfCMIvdXAFdhzA" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_iPU_0UXVEfCMIvdXAFdhzA" id="(0.54,0.14)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
